name : Docker Build

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Step up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build the Docker Buildx
              uses: docker/buildx-push-action@v6
              with:
                context: .
                push: false
                tags: test-docker-build:latest